//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public System.Guid id { get; set; }
        public System.Guid contactId { get; set; }
        public string addressLine1 { get; set; }
        public string addressLine2 { get; set; }
        public string addressCity { get; set; }
        public string addressCountry { get; set; }
        public string addressStateCounty { get; set; }
        public string addressZip { get; set; }
    
        public virtual Contact Contact { get; set; }
    }
}
